name: validations
description: Null-safety Validations for dart models.
version: 1.0.0
homepage: https://github.com/dartlib/validations.git
author: Rob Halff <rob.halff@gmail.com>

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  decimal: 2.3.2
  meta: 1.9.1
  intl: 0.18.0
  validators: 3.0.0

dev_dependencies:
  coverage: 1.6.3
  build_runner:
  validations_generator:
    path: ../validations_generator
  pedantic: 1.11.1
  test: 1.23.1
#  test_coverage: ^0.3.0
